version: '3.8'
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: devdb

  test-db:
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: test_postgres_pw
      POSTGRES_DB: testdb